### ISSUE TITLE
Consider making into a pod using `network=host`

### ISSUE THREAD

**Issue by bashlund** [simplenetes-io/proxy#1]
Since podman added `network=host` support some time ago we should be able to have the proxy as a regular pod instead of as an executable.

**Comment by filippsen** [comment]
Indeed. From the examples section:
```
$ podman run --help
[...]
  podman run --network=host imageID dnf -y install java   
```

Man page:
```
  • host: use the Podman host network stack. Note: the host mode gives the container full access
to local system services such as D-bus and is therefore considered insecure;
```

**Comment by bashlund** [comment]
At closer inspection I see that the proxy read the `.conf` files in the host root. This means we would need to mount those files into the pod which seems to add complexity. So my suggestion is to just keep the proxy pod as a native executable as it is.
